name: Deploy Demo to GH Pages

on:
  push:
    paths:
      - "demo/*"
    branches-ignore:
      - "dependabot/*"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_demo:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: 👷 Checkout Repo
        uses: actions/checkout@v6

      - name: 🏗️ Setup Pages
        uses: actions/configure-pages@v6

      - name: 📦 Create and Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "demo/"

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
