name: Deploy Cloudflare Worker

on:
  push:
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".github/dependabot.yml"
      - ".editorConfig"
    branches-ignore:
      - "dependabot/*"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: ${{ vars.NODE_VERSION || '26.x' }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 👷 Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 🏗️ Setup Node.js ${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: 🚀 Deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
